import React, { useState, useEffect, useCallback } from 'react';
import { Plus, Pencil, Trash2, MapPin } from 'lucide-react';
import { Button } from '../../../../ui/shadcn/button';
import { Badge } from '../../../../ui/shadcn/badge';
import { Skeleton } from '../../../../ui/shadcn/skeleton';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '../../../../ui/shadcn/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '../../../../ui/shadcn/alert-dialog';

const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:3001';

function getAuthHeader() {
  const token = localStorage.getItem('authToken');
  return token ? { Authorization: `Bearer ${token}` } : {};
}

/**
 * Intersection Configuration Panel
 * Allows admins to create, edit, and delete intersections
 * intersection_id is auto-generated by the backend
 */
export function IntersectionConfig() {
  const [intersections, setIntersections] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [editingId, setEditingId] = useState(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    latitude: '',
    longitude: '',
    cuipSlug: '',
  });

  // Fetch intersections
  useEffect(() => {
    const fetchIntersections = async () => {
      try {
        setLoading(true);
        const res = await fetch(`${API_URL}/api/intersections`, {
          headers: getAuthHeader(),
        });

        if (!res.ok) throw new Error('Failed to fetch intersections');

        const data = await res.json();
        setIntersections(data);
        setError(null);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchIntersections();
  }, []);

  const openDialog = (intersection = null) => {
    if (intersection) {
      const coords = intersection.ref_point?.coordinates || [0, 0];
      setFormData({
        name: intersection.name,
        description: intersection.description || '',
        latitude: coords[1].toString(),
        longitude: coords[0].toString(),
        cuipSlug: intersection.cuip_slug || '',
      });
      setEditingId(intersection.intersection_id);
    } else {
      setFormData({
        name: '',
        description: '',
        latitude: '',
        longitude: '',
        cuipSlug: '',
      });
      setEditingId(null);
    }
    setIsDialogOpen(true);
  };

  const handleSave = useCallback(async () => {
    try {
      const lat = parseFloat(formData.latitude);
      const lon = parseFloat(formData.longitude);

      if (!formData.name || isNaN(lat) || isNaN(lon)) {
        alert('Name and valid coordinates are required');
        return;
      }

      if (lat < -90 || lat > 90 || lon < -180 || lon > 180) {
        alert('Invalid coordinates. Latitude: -90 to 90, Longitude: -180 to 180');
        return;
      }

      const body = {
        name: formData.name,
        description: formData.description || null,
        ref_point: {
          type: 'Point',
          coordinates: [lon, lat],
        },
        cuip_slug: formData.cuipSlug || null,
      };

      const method = editingId ? 'PUT' : 'POST';
      const url = editingId
        ? `${API_URL}/api/intersections/${editingId}`
        : `${API_URL}/api/intersections`;

      const res = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeader(),
        },
        body: JSON.stringify(body),
      });

      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || 'Failed to save intersection');
      }

      const saved = await res.json();

      if (editingId) {
        setIntersections((prev) =>
          prev.map((i) => (i.intersection_id === editingId ? saved : i))
        );
      } else {
        setIntersections((prev) => [saved, ...prev]);
      }

      setIsDialogOpen(false);
    } catch (err) {
      alert(`Error: ${err.message}`);
    }
  }, [formData, editingId]);

  const handleDelete = useCallback(async (intersectionId) => {
    try {
      const res = await fetch(`${API_URL}/api/intersections/${intersectionId}`, {
        method: 'DELETE',
        headers: getAuthHeader(),
      });

      if (!res.ok) throw new Error('Failed to delete intersection');

      setIntersections((prev) => prev.filter((i) => i.intersection_id !== intersectionId));
    } catch (err) {
      alert(`Error: ${err.message}`);
    }
  }, []);

  if (loading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-12 w-full" />
        <Skeleton className="h-12 w-full" />
        <Skeleton className="h-12 w-full" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-foreground mb-2">Intersections</h2>
          <p className="text-sm text-muted-foreground">
            Manage traffic intersections. IDs are auto-generated.
          </p>
        </div>
        <Button onClick={() => openDialog()} className="gap-2">
          <Plus className="w-4 h-4" />
          New Intersection
        </Button>
      </div>

      {error && (
        <div className="p-3 bg-red-950 text-red-200 rounded text-sm">
          {error}
        </div>
      )}

      <div className="space-y-2">
        {intersections.map((intersection) => (
          <div
            key={intersection.intersection_id}
            className="flex items-center justify-between p-3 rounded border border-neutral-700 bg-neutral-800/50 hover:bg-neutral-800/80 transition-colors"
          >
            <div className="flex items-center gap-3 flex-1">
              <MapPin className="w-4 h-4 text-neutral-400" />
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <p className="font-medium text-sm text-neutral-100">{intersection.name}</p>
                  <Badge variant="secondary" className="text-xs font-mono">
                    ID: {intersection.intersection_id}
                  </Badge>
                </div>
                {intersection.ref_point?.coordinates && (
                  <p className="text-xs text-neutral-400 mt-0.5">
                    {intersection.ref_point.coordinates[1].toFixed(4)}, {intersection.ref_point.coordinates[0].toFixed(4)}
                  </p>
                )}
                {intersection.description && (
                  <p className="text-xs text-neutral-500 mt-1">{intersection.description}</p>
                )}
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Badge variant={intersection.status === 'confirmed' ? 'default' : 'secondary'} className="text-xs">
                {intersection.status}
              </Badge>
              <Button
                size="sm"
                variant="outline"
                onClick={() => openDialog(intersection)}
                className="h-8"
              >
                <Pencil className="w-3 h-3" />
              </Button>
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <Button size="sm" variant="destructive" className="h-8">
                    <Trash2 className="w-3 h-3" />
                  </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Delete Intersection</AlertDialogTitle>
                    <AlertDialogDescription>
                      Delete {intersection.name}? All associated lanes, zones, and cameras will also be deleted. This cannot be undone.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction
                      onClick={() => handleDelete(intersection.intersection_id)}
                      className="bg-red-600 hover:bg-red-700"
                    >
                      Delete
                    </AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </div>
          </div>
        ))}

        {intersections.length === 0 && !error && (
          <div className="text-center p-8 text-muted-foreground">
            No intersections yet. Click "New Intersection" to create one.
          </div>
        )}
      </div>

      {/* Dialog for creating/editing intersections */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>{editingId ? 'Edit Intersection' : 'Create Intersection'}</DialogTitle>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <label className="text-xs font-medium text-neutral-300">
                Name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                placeholder="e.g., MLK & Georgia"
                value={formData.name}
                onChange={(e) => setFormData((p) => ({ ...p, name: e.target.value }))}
                className="w-full mt-1 px-3 py-2 rounded bg-neutral-700 border border-neutral-600 text-sm text-neutral-100 placeholder-neutral-500"
              />
            </div>

            <div>
              <label className="text-xs font-medium text-neutral-300">Description</label>
              <textarea
                placeholder="Optional description"
                value={formData.description}
                onChange={(e) => setFormData((p) => ({ ...p, description: e.target.value }))}
                className="w-full mt-1 px-3 py-2 rounded bg-neutral-700 border border-neutral-600 text-sm text-neutral-100 placeholder-neutral-500 h-20 resize-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-medium text-neutral-300">
                  Latitude <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  placeholder="e.g., 33.7490"
                  step="0.0001"
                  min="-90"
                  max="90"
                  value={formData.latitude}
                  onChange={(e) => setFormData((p) => ({ ...p, latitude: e.target.value }))}
                  className="w-full mt-1 px-3 py-2 rounded bg-neutral-700 border border-neutral-600 text-sm text-neutral-100 placeholder-neutral-500"
                />
              </div>
              <div>
                <label className="text-xs font-medium text-neutral-300">
                  Longitude <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  placeholder="e.g., -84.3880"
                  step="0.0001"
                  min="-180"
                  max="180"
                  value={formData.longitude}
                  onChange={(e) => setFormData((p) => ({ ...p, longitude: e.target.value }))}
                  className="w-full mt-1 px-3 py-2 rounded bg-neutral-700 border border-neutral-600 text-sm text-neutral-100 placeholder-neutral-500"
                />
              </div>
            </div>

            <div>
              <label className="text-xs font-medium text-neutral-300">CUIP Slug</label>
              <input
                type="text"
                placeholder="e.g., MLK_Georgia"
                value={formData.cuipSlug}
                onChange={(e) => setFormData((p) => ({ ...p, cuipSlug: e.target.value }))}
                className="w-full mt-1 px-3 py-2 rounded bg-neutral-700 border border-neutral-600 text-sm text-neutral-100 placeholder-neutral-500"
              />
              <p className="text-xs text-neutral-500 mt-1">Links to live CUIP stream data</p>
            </div>

            {editingId && (
              <div className="p-2 bg-neutral-800 rounded text-xs text-neutral-400">
                Intersection ID: <span className="font-mono text-neutral-200">{editingId}</span>
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleSave}>
              {editingId ? 'Update' : 'Create'} Intersection
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
